In [20]:
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv('../../../Data/Fish/capture-fisheries-vs-aquaculture.csv')

In [22]:
df.drop(df[df['Code'] != 'USA', ].index, inplace=True)

In [23]:
df.drop(['Entity'], axis=1, inplace=True)

In [24]:
df.columns

Index(['Code', 'Year', 'Aquaculture production (metric tons)',
       'Capture fisheries production (metric tons)'],
      dtype='object')

In [25]:
df.rename(columns = {'Aquaculture production (metric tons)':'Aquaculture Production', 'Capture fisheries production (metric tons)':'Captured Fish'}, inplace=True)

In [26]:
df

      Code  Year  Aquaculture Production  Captured Fish
12022  USA  1960                104421.0      2755715.0
12023  USA  1961                102547.0      2979093.0
12024  USA  1962                109961.0      2995674.0
12025  USA  1963                122697.0      2741650.0
12026  USA  1964                123884.0      2585660.0
12027  USA  1965                132578.0      2702785.0
12028  USA  1966                114236.0      2495433.0
12029  USA  1967                127299.0      2377789.0
12030  USA  1968                131115.0      2470105.0
12031  USA  1969                116768.0      2478221.0
12032  USA  1970                168681.0      2836550.0
12033  USA  1971                165590.0      2917107.0
12034  USA  1972                173630.0      2810040.0
12035  USA  1973                170320.0      2836981.0
12036  USA  1974                167039.0      2919015.0
12037  USA  1975                218459.0      2876146.0
12038  USA  1976                183907.0      3111419.0
12039  USA  1977                174310.0      3065974.0
12040  USA  1978                158795.0      3502537.0
12041  USA  1979                138990.0      3609656.0
12042  USA  1980                168365.0      3727627.0
12043  USA  1981                230111.0      3725240.0
12044  USA  1982                261725.0      3977879.0
12045  USA  1983                268483.0      4186687.0
12046  USA  1984                326453.0      4763710.0
12047  USA  1985                323573.0      4744131.5
12048  USA  1986                372191.0      4910476.0
12049  USA  1987                383259.0      5745394.0
12050  USA  1988                357657.0      5754885.0
12051  USA  1989                369252.0      5579698.5
12052  USA  1990                315727.0      5781091.5
12053  USA  1991                363083.0      5373133.0
12054  USA  1992                413844.0      5473939.5
12055  USA  1993                416913.0      5817721.5
12056  USA  1994                391412.0      5846727.5
12057  USA  1995                413454.0      5414226.0
12058  USA  1996                393346.0      5268586.0
12059  USA  1997                438356.0      5385731.0
12060  USA  1998                445119.0      5059144.0
12061  USA  1999                479212.0      5205206.0
12062  USA  2000                456830.0      5041558.0
12063  USA  2001                480362.0      5275155.0
12064  USA  2002                498899.0      5326987.0
12065  USA  2003                545971.0      5345396.0
12066  USA  2004                607570.0      5363263.0
12067  USA  2005                513920.0      5320894.0
12068  USA  2006                519967.0      5311208.0
12069  USA  2007                526045.0      5189908.0
12070  USA  2008                501326.0      4606530.0
12071  USA  2009                481224.0      4527104.0
12072  USA  2010                496699.0      4687648.0
12073  USA  2011                397292.0      5491330.0
12074  USA  2012                420386.0      5338928.0
12075  USA  2013                429011.0      5581776.0
12076  USA  2014                421189.0      5476248.0
12077  USA  2015                426002.0      5472360.0
12078  USA  2016                444679.0      5463707.0
12079  USA  2017                439670.0      5501797.0
12080  USA  2018                468185.0      5353303.0

In [27]:
df.to_csv('../../../Data/Fish/farmsandcapture_cleaned.csv', index=False)