In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
pd.set_option('display.max_columns', None)

In [44]:
df = pd.read_csv('../../Data/final_csv_all_data.csv')

In [45]:
df

,Entity,Code,Year,kg_per_yr_per_capita,Production_in_tons,Population (historical estimates),Life_Expectancy_years,continent
0,Afghanistan,AFG,1961,0.030559,300.0,8790140,32.96,Asia
1,Afghanistan,AFG,1962,0.030578,300.0,8969055,33.47,Asia
2,Afghanistan,AFG,1963,0.030598,300.0,9157463,33.97,Asia
3,Afghanistan,AFG,1964,0.030614,300.0,9355510,34.46,Asia
4,Afghanistan,AFG,1965,0.030627,300.0,9565154,34.95,Asia
...,...,...,...,...,...,...,...,...
9305,Zimbabwe,ZWE,2016,3.679239,25800.0,14452705,60.29,Africa
9306,Zimbabwe,ZWE,2017,3.397224,26800.0,14751101,60.81,Africa
9307,Zimbabwe,ZWE,2018,3.117559,32300.0,15052191,61.20,Africa
9308,Zimbabwe,ZWE,2019,2.870986,29230.0,15354606,61.49,Africa
9309,Zimbabwe,ZWE,2020,2.817092,29230.0,15669663,61.74,Africa

In [46]:
# df = df[df['Code'] == 'USA'].reset_index(drop=True)
df

,Entity,Code,Year,kg_per_yr_per_capita,Production_in_tons,Population (historical estimates),Life_Expectancy_years,continent
0,Afghanistan,AFG,1961,0.030559,300.0,8790140,32.96,Asia
1,Afghanistan,AFG,1962,0.030578,300.0,8969055,33.47,Asia
2,Afghanistan,AFG,1963,0.030598,300.0,9157463,33.97,Asia
3,Afghanistan,AFG,1964,0.030614,300.0,9355510,34.46,Asia
4,Afghanistan,AFG,1965,0.030627,300.0,9565154,34.95,Asia
...,...,...,...,...,...,...,...,...
9305,Zimbabwe,ZWE,2016,3.679239,25800.0,14452705,60.29,Africa
9306,Zimbabwe,ZWE,2017,3.397224,26800.0,14751101,60.81,Africa
9307,Zimbabwe,ZWE,2018,3.117559,32300.0,15052191,61.20,Africa
9308,Zimbabwe,ZWE,2019,2.870986,29230.0,15354606,61.49,Africa
9309,Zimbabwe,ZWE,2020,2.817092,29230.0,15669663,61.74,Africa

In [47]:
X = df[['Production_in_tons', 'kg_per_yr_per_capita']]
y = df['Life_Expectancy_years']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
# print('Mean Squared Error:', mse)
print(model.score(X_test, y_test))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').